services:
  postgres:
    image: postgres:15-alpine
    container_name: metrics_postgres
    environment:
      POSTGRES_USER: metrics_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: metrics_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  java-service:
    build:
      context: ./aggregator-service    # путь к папке с Dockerfile Java
    container_name: aggregator_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/metrics_db
      SPRING_DATASOURCE_USERNAME: metrics_user
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres

  go-collector:
    build:
      context: ./codemetrics-fetcher    # путь к папке с Dockerfile Go
    container_name: go_collector
    ports:
      - "8090:8080"                  # порт внутри Go-контейнера
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: metrics_db
      POSTGRES_USER: metrics_user
      POSTGRES_PASSWORD: 1234
    depends_on:
      - postgres

volumes:
  pg_data: